<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>

    <IsPackable>false</IsPackable>
    <GenerateProgramFile>false</GenerateProgramFile>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="TestUtils.fs" />
    <Compile Include="StringsTests.fs" />
    <Compile Include="ThrottlingTests.fs" />
    <Compile Include="MicrobrokerCountTests.fs" />
    <Compile Include="MicrobrokerProxyTests.fs" />
    <Compile Include="MicrobrokerMessagesTests.fs" />
    <Compile Include="DependencyInjectionTests.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\microbroker.client\Microbroker.Client.fsproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FsCheck.Xunit.v3" Version="3.4.0" />
    <PackageReference Include="FsUnit" Version="7.1.1" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" Version="18.11.2" />
    <PackageReference Include="Microsoft.Testing.Extensions.TrxReport" Version="2.4.1" />
    <PackageReference Include="NSubstitute" Version="6.2.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="4.0.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="xunit.v3" Version="4.0.1" />
  </ItemGroup>
</Project>
